import Menu from '../../components/menu'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Cadastro de Tarefas',
    description: 'Generated by create next app',
  }
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className={inter.className}>
            <Menu />
          {children}
          </body>
      </html>
    )
  }